### ISSUE TITLE
include unique DESI identifier

### ISSUE THREAD

**Issue by moustakas** [moustakas/desi-photometry#18]
@akremin can you please provide the code needed to build the DESI identifier proposed during the data systems calls?

**Comment by akremin** [comment]
This is now done in desiutil: `https://github.com/desihub/desiutil/pull/203`.

The function is `desiutil.names.radec_to_desiname()` and is called with target_ra and target_dec as arguments.

Tags of desiutil >= 3.4.2 will have it.

**Comment by moustakas** [comment]
Thank you @akremin. This issue was implemented in #19.
