### ISSUE TITLE
Inconsistent type for gaia_astrometric_params_solved

### ISSUE THREAD

**Issue by weaverba137** [moustakas/desi-photometry#8]
In the tractorphot files, the column `gaia_astrometric_params_solved` is a small integer (FITS type B), but in the targetphot files it is a boolean (FITS type L).  Is this intentional?

**Comment by weaverba137** [comment]
The [official tractor data model](https://www.legacysurvey.org/dr9/catalogs/) also has `gaia_astrometric_params_solved` with type `uint8`, which is the same as FITS type B.

**Comment by weaverba137** [comment]
`desispec.io.photo.tractorphot_datamodel()` has [int8](https://github.com/desihub/desispec/blob/fd654d988b8aa8795984590a4c2fae1d8d619ea6/py/desispec/io/photo.py#L272), while `desispec.io.photo.targetphot_datamodel()` has [uint8](https://github.com/desihub/desispec/blob/fd654d988b8aa8795984590a4c2fae1d8d619ea6/py/desispec/io/photo.py#L574), so there's already an inconsistency there.  But if the `from_file` option is used, both the tractor file and the target file that are used in that case have FITS type B for that column.

**Comment by moustakas** [comment]
Done in https://github.com/desihub/desispec/pull/1971.
