### ISSUE TITLE
regenerate v2.0 catalogs

### ISSUE THREAD

**Issue by moustakas** [moustakas/desi-photometry#9]
Now that the fiberassign files have been patched, regenerate the VACs.

**Comment by moustakas** [comment]
@weaverba137 I'm working on this ticket now. Do you want me to use the `latest-photometry` branch or work in a new branch.

**Comment by weaverba137** [comment]
Thank you for reminding me. It turns out I didn't actually need the things that `latest-photometry` was intended for, so it can be discarded.  However, before you do that, take a look at the README file. I found some typos that are fixed on the branch.
